--- #YAML:1.0
name:                PAB3-DB-Driver-Mysql
version:             1.07
abstract:            A Perl5 wrapper for MySQL and a driver for the PAB3::DB class
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
